services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: analytics_db
    ports:
      - "5432:5432"
    networks:
      - network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d analytics_db"]
      interval: 5s
      timeout: 3s
      retries: 5
  
  pgadmin:
    image: dpage/pgadmin4:8.0
    restart: unless-stopped
    networks:
      - network
    ports:
      - "${PGADMIN_LISTEN_PORT:-5050}:${PGADMIN_LISTEN_PORT:-5050}"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    env_file:
      - ../.env
    depends_on:
      postgres:
        condition: service_healthy

networks:
  network:
    driver: bridge

volumes:
  pgadmin-data:
